# Generated by Django 2.1.4 on 2018-12-13 16:04

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_api_secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', '사진'), ('video', '동영상')], max_length=5)),
                ('ext', models.CharField(max_length=5)),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('last_tweet_id', models.BigIntegerField(blank=True, null=True)),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
                ('rate_limit_remaining', models.IntegerField(blank=True, null=True)),
                ('rate_limit_reset', models.DateTimeField(blank=True, null=True)),
                ('mode', models.SmallIntegerField(choices=[(1, '즉시 업로드(두벌식 영타 변환)'), (2, '나중에 업로드(텍스트 직접 입력)')], default=2, verbose_name='동작 방식')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdnlcl_app.TwitterUser'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tmdnlcl_app.Tweet'),
        ),
    ]
