# Generated by Django 2.1.4 on 2018-12-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdnlcl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='batch_delay',
            field=models.IntegerField(default=5),
        ),
    ]
