# Generated by Django 2.1.4 on 2018-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdnlcl_app', '0002_appsetting_batch_delay'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
