# Generated by Django 2.1.4 on 2018-12-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tmdnlcl_app', '0003_twitteruser_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='last_update',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
